call_time/theater/getdata/urls.py
from . import views
from django.urls import path, re_path
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'getdata'

urlpatterns = [
    path('home/', views.HomeView.as_view(), name='home'),
    path('venues/', views.VenueView.as_view(), name='venues'),
    path('user/login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('documents/', views.UploadsView.as_view(), name='documents'),
    # /info/23/
    re_path(r'^info/(?P<pk>[0-9]+)/$', views.InfoView.as_view(), name='info'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('privacy/', views.PrivacyChange.as_view(), name='privacy'),
    path('email-notice/', views.EmailNoticeChange.as_view(), name='email-notice'),
    path('alert/', views.SendAlert.as_view(), name='alert'),
    path('user/register/', views.UserFormView.as_view(), name='register'),
    path('user/registercompany/', views.CompanyFormView.as_view(), name='registercompany'),
    path('performer/add/', views.AddPerformer.as_view(), name='add-performer'),
    path('show/add/', views.ShowCreate.as_view(), name='show-add'),
    path('role/add/', views.RoleCreate.as_view(), name='role-add'),
    path('call/add/', views.CallCreate.as_view(), name='call-add'),
    path('quick/add/', views.QuickCreate.as_view(), name='quick-add'),
    path('venue/add/', views.VenueCreate.as_view(), name='venue-add'),
    path('documents/add/', views.UploadsCreate.as_view(), name='documents-add'),
    path('schedule/', views.CreatePDF.as_view(), name='schedule'),
    path('schedule-view/', views.ViewPDF.as_view(), name='schedule-view'),
    path('staff/add/', views.AddStaff.as_view(), name='staff-add'),
    path('staffinfo/', views.StaffView.as_view(), name='staffinfo'),
    re_path(r'^showinfo/(?P<pk>[0-9]+)/$', views.ShowInfoView.as_view(), name='showinfo'),
    re_path(r'^roleinfo/(?P<pk>[0-9]+)/$', views.RoleInfoView.as_view(), name='roleinfo'),
    re_path(r'^callinfo/(?P<pk>[0-9]+)/$', views.CallInfoView.as_view(), name='callinfo'),
    re_path(r'^venueinfo/(?P<pk>[0-9]+)/$', views.VenueInfoView.as_view(), name='venueinfo'),
    re_path(r'^venue/(?P<pk>[0-9]+)/$', views.VenueUpdate.as_view(), name='venue-update'),
    re_path(r'^venue/(?P<pk>[0-9]+)/delete/$', views.VenueDelete.as_view(), name='venue-delete'),
    re_path(r'^quick/(?P<pk>[0-9]+)/$', views.QuickUpdate.as_view(), name='quick-update'),
    re_path(r'^quick/(?P<pk>[0-9]+)/delete/$', views.QuickDelete.as_view(), name='quick-delete'),
    re_path(r'^call/(?P<pk>[0-9]+)/$', views.CallUpdate.as_view(), name='call-update'),
    re_path(r'^call/(?P<pk>[0-9]+)/delete/$', views.CallDelete.as_view(), name='call-delete'),
    re_path(r'^performer/(?P<pk>[0-9]+)/$', views.PerformerUpdate.as_view(), name='performer-update'),
    # re_path(r'^performer/(?P<pk>[0-9]+)/delete/$', views.PerformerDelete.as_view(), name='performer-delete'),
    re_path(r'^documents/(?P<pk>[0-9]+)/$', views.UploadsUpdate.as_view(), name='documents-update'),
    re_path(r'^documents/(?P<pk>[0-9]+)/delete/$', views.UploadsDelete.as_view(), name='documents-delete'),
    re_path(r'^show/(?P<pk>[0-9]+)/$', views.ShowUpdate.as_view(), name='show-update'),
    re_path(r'^show/(?P<pk>[0-9]+)/delete/$', views.ShowDelete.as_view(), name='show-delete'),
    re_path(r'^role/(?P<pk>[0-9]+)/$', views.RoleUpdate.as_view(), name='role-update'),
    re_path(r'^role/(?P<pk>[0-9]+)/delete/$', views.RoleDelete.as_view(), name='role-delete'),
    re_path(r'^company/(?P<pk>[0-9]+)/$', views.CompanyUpdate.as_view(), name='company-update'),
    re_path(r'^company/(?P<pk>[0-9]+)/performers$', views.CompanyPerformersUpdate.as_view(), name='companyperformers-update'),
    re_path(r'^staff/(?P<pk>[0-9]+)/$', views.StaffUpdate.as_view(), name='staff-update'),
    re_path(r'^staff/(?P<pk>[0-9]+)/delete/$', views.StaffDelete.as_view(), name='staff-delete'),
    re_path(r'^artists/(?P<pk>[0-9]+)/$', views.ArtistsView.as_view(), name='artists'),
    re_path(r'^artists/(?P<pk>[0-9]+)/delete/$', views.CompanyPerformersDeleteAll.as_view(), name='artists-delete-all'),
    path('addme/', views.AddLink.as_view(), name='addme'),
    re_path(r'^categoryinfo/(?P<pk>[0-9]+)/$', views.CategoryInfo.as_view(), name='categoryinfo'),
    path('category/add/', views.CategoryCreate.as_view(), name='category-add'),
    re_path(r'^category/(?P<pk>[0-9]+)/$', views.CategoryUpdate.as_view(), name='category-update'),
    re_path(r'^category/(?P<pk>[0-9]+)/delete/$', views.CategoryDelete.as_view(), name='category-delete'),
    re_path(r'^user/(?P<pk>[0-9]+)/$', views.UserUpdate.as_view(), name='user-update'),
    re_path(r'^logo/(?P<pk>[0-9]+)/$', views.LogoUpdate.as_view(), name='logo'),
    path('conflict/add/', views.ConflictCreate.as_view(), name='conflict-add'),
    re_path(r'^conflict/(?P<pk>[0-9]+)/$', views.ConflictUpdate.as_view(), name='conflict-update'),
    re_path(r'^conflict/(?P<pk>[0-9]+)/delete/$', views.ConflictDelete.as_view(), name='conflict-delete'),
    re_path(r'^conflictinfo/(?P<pk>[0-9]+)/$', views.ConflictInfo.as_view(), name='conflictinfo'),
    path('conflicts/', views.ConflictView.as_view(), name='conflicts'),
    path(r'^join/$', views.JoinChange.as_view(), name='join'),
    path('feedback/', views.Feedback.as_view(), name='feedback'),

]

call_time/theater/theater/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from getdata import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('getdata/', include('getdata.urls')),
    path('accounts/profile/', views.HomeView.as_view()),
    path('accounts/', include("django.contrib.auth.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

call_time/theater/getdata/models.py
from django.db import models
import datetime
from django.urls import reverse
from django import forms
from gdstorage.storage import GoogleDriveStorage

# Define Google Drive Storage
gd_storage = GoogleDriveStorage()

# Create your models here.
class Performers(models.Model):
    username = models.CharField(max_length=128, unique=True, null=False)
    first_name = models.CharField(max_length=128, null=False)
    last_name = models.CharField(max_length=128, null=False)
    email = models.CharField(max_length=128, unique=True, null=False)
    phone = models.CharField(max_length=128, unique=True, null=True, blank=True)
    email_notifications = models.BooleanField(default=True)
    public_profile = models.BooleanField(default=True)

    def get_absolute_url(self):
        return reverse('getdata:profile')

    def __str__(self):
        return self.first_name[0].upper() + ". " + self.last_name

class Company(models.Model):
    username = models.CharField(max_length=128, unique=True, null=False)
    name = models.CharField(max_length=128, unique=True, null=False)
    email = models.CharField(max_length=128, unique=True, null=False)
    performers = models.ManyToManyField(Performers, blank=True, null=True)
    logo = models.FileField(null=True, blank=True, upload_to='calltime-uploads', storage=gd_storage)
    join = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('getdata:profile')

class Staff(models.Model):
    first_name = models.CharField(max_length=128, null=False)
    last_name = models.CharField(max_length=128, null=False)
    email = models.CharField(max_length=128, null=False)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)

    def get_absolute_url(self):
            return reverse('getdata:staffinfo')

    def __str__(self):
        return self.first_name[0].upper() + ". " + self.last_name

class Shows(models.Model):
    title = models.CharField(max_length=128, null=False)
    rehearsal_start = models.DateField(null=True, blank=True)
    show_open = models.DateField(null=False)
    director_id = models.ForeignKey(Staff, on_delete=models.SET_NULL, null=True, blank=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, null=True)

    def get_absolute_url(self):
            return reverse('getdata:showinfo', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

class Category(models.Model):
    name = models.CharField(max_length=128, null=False)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    description = models.TextField(null=True, blank=True)

    def get_absolute_url(self):
            return reverse('getdata:profile')

    def __str__(self):
        return self.name.replace(" ", "")

class Roles(models.Model):
    name = models.CharField(max_length=128, null=False)
    show_id = models.ForeignKey(Shows, on_delete=models.CASCADE)
    performer_id = models.ForeignKey(Performers, on_delete=models.SET_NULL, null=True, blank=True)
    category = models.ManyToManyField(Category, blank=True, null=True)

    def get_absolute_url(self):
            return reverse('getdata:roleinfo', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name + " - from: " + self.show_id.title + " - performer: " + str(self.performer_id)


class RehearsalVenues(models.Model):
    name = models.CharField(max_length=128, null=False)
    location = models.CharField(max_length=128, null=False)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, null=True)

    def get_absolute_url(self):
            return reverse('getdata:venueinfo', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name

class CallTime(models.Model):
    show_id_id = models.ForeignKey(Shows, on_delete=models.CASCADE)
    venue_id = models.ForeignKey(RehearsalVenues, on_delete=models.SET_NULL, null=True, blank=True)
    date = models.DateField(null=False)
    start_time = models.TimeField(null=False)
    end_time = models.TimeField(null=True, blank=True)
    performers = models.ManyToManyField(Performers, null=True, blank=True)
    notes = models.TextField(null=True, blank=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, null=True)
    staff = models.ManyToManyField(Staff, null=True, blank=True)
    headline = models.CharField(max_length=128, null=True, blank=True)

    def get_absolute_url(self):
            return reverse('getdata:callinfo', kwargs={'pk': self.pk})

    def __str__(self):
        return str(self.date) + ": " + str(self.start_time)  + " - " + str(self.end_time)

class QuickCall(models.Model):
    call = models.ForeignKey(CallTime, on_delete=models.CASCADE)
    start_time = models.TimeField(null=False)
    end_time = models.TimeField(null=True, blank=True)
    performers = models.ManyToManyField(Performers, null=True, blank=True)
    details = models.CharField(max_length=128, null=True, blank=True)

    def get_absolute_url(self):
            return reverse('getdata:callinfo', kwargs={'pk': self.call.pk})

    def __str__(self):
        return str(self.start_time)  + " - " + str(self.end_time)

class Uploads(models.Model):
    name = models.CharField(max_length=128)
    details = models.TextField(null=True, blank=True)
    file = models.FileField(upload_to='calltime-uploads', storage=gd_storage)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)

    def get_absolute_url(self):
            return reverse('getdata:documents')

    def __str__(self):
        return self.name

class Conflict(models.Model):
    performer_id = models.ForeignKey(Performers, on_delete=models.CASCADE)
    start_date = models.DateField(null=False)
    end_date = models.DateField(null=True, blank=True)
    start_time = models.TimeField(null=True, blank=True)
    end_time = models.TimeField(null=True, blank=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('getdata:conflictinfo', kwargs={'pk': self.pk})

    def __str__(self):
        return self.performer_id.last_name + "'s Conflict on " + str(self.start_date)

call_time/theater/getdata/forms.py
from django import forms
from .models import Performers
from django.contrib.auth.models import User

class NameForm(forms.ModelForm):
    name = forms.CharField(label="Name", max_length=128)
    password = forms.CharField(widget=forms.PasswordInput)
    retype_password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'name', 'email', 'password']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    retype_password = forms.CharField(widget=forms.PasswordInput)
    first_name = forms.CharField(max_length=128)
    last_name = forms.CharField(max_length=128)
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password']

class AddPerformerForm(forms.ModelForm):
    company = forms.CharField(max_length=128)
    class Meta:
        model = User
        fields = ['company', 'email']

class AddStaffForm(forms.ModelForm):
    first_name = forms.CharField(max_length=128)
    last_name = forms.CharField(max_length=128)
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

call_time/theater/getdata/templates/documents.html
{% extends 'base.html' %}
{% block body %}
{% if error_message %}
    <h1>{{ error_message }}</h1>
{% endif %}
<br>
<div class="container-fluid pl-md-5">
    <div class="row">
        <div class="col-sm-10 text-center">
            <h1>Documents</h1>
        </div>
    </div>
    <hr>
    Note: The mobile app is unable to use the download option for documents. Use a web browser to download docs if on mobile.
    <br>
    <div class="row">
        <div class="col-sm-12">
            {% if user.groups.all.last.name == 'Company' %}
                <hr>
                <h3><a href="{% url 'getdata:documents-add' %}?{{ self.id }}"><i class="fa fa-plus no-outline"></i> Upload a new file</a></h3>
                <hr>
                <h2><u>{{ self.name }}</u></h2>
                {% for doc in self.uploads_set.all %}
                    <br>
                    <h2>
                    <a class='docLink' data-title='{{ doc.name }}' data-url="{{ doc.file.url|cut:'download' }}" data-name="{{ doc.file }}" data-toggle="modal" data-target="#docModal" aria-hidden="true"><i class="fa fa-file no-outline"></i> {{ doc.name }}</a>&emsp;<a href="{{ doc.file.url }}" download><i class="fa fa-download"></i></a><br>
                    {{ doc.details }}
                    </h2>
                    <form style="display: inline; margin-left: 5%;" action="{% url 'getdata:documents-update' doc.id %}">
                        {% csrf_token %}
                        <input type="hidden" name="doc_id" value="{{ doc.id }}">&nbsp;
                        <button type="submit" class="btn btn-secondary">
                            <i class="fa fa-wrench"></i>
                        </button>&nbsp;
                    </form>&nbsp;
                    <form style="display: inline" action="{% url 'getdata:documents-delete' doc.id %}">
                        {% csrf_token %}
                        <input type="hidden" name="doc_id" value="{{ doc.id }}">
                        <button type="submit" class="btn btn-danger">
                            <i class="fa fa-trash"></i>
                        </button>
                    </form>
                    <br>
                {% endfor %}
                <hr>
                {% for s in staff %}
                    <h2><u>{{ s.company }}</u></h2>
                    {% for doc in s.company.uploads_set.all %}
                        <br>
                        <h2>
                        <a class='docLink' data-title='{{ doc.name }}' data-url="{{ doc.file.url|cut:'download' }}" data-name="{{ doc.file }}" data-toggle="modal" data-target="#docModal" aria-hidden="true"><i class="fa fa-file no-outline"></i> {{ doc.name }}</a>&emsp;<a href="{{ doc.file.url }}" download><i class="fa fa-download"></i></a><br>
                        {{ doc.details }}
                        </h2>
                        <form style="display: inline; margin-left: 5%;" action="{% url 'getdata:documents-update' doc.id %}">
                            {% csrf_token %}
                            <input type="hidden" name="doc_id" value="{{ doc.id }}">&nbsp;
                            <button type="submit" class="btn btn-secondary">
                                <i class="fa fa-wrench"></i>
                            </button>&nbsp;
                        </form>&nbsp;
                        <form style="display: inline" action="{% url 'getdata:documents-delete' doc.id %}">
                            {% csrf_token %}
                            <input type="hidden" name="doc_id" value="{{ doc.id }}">
                            <button type="submit" class="btn btn-danger">
                                <i class="fa fa-trash"></i>
                            </button>
                        </form>
                        <br>
                    {% endfor %}
                {% endfor %}
            {% elif user.groups.all.last.name == 'Artist' %}
                <hr>
                {% for company in companies %}
                    {% for performer in company.performers.all %}
                        {% if performer.username == user.username %}
                            <h2><u>{{ company }}</u></h2><br>
                            {% for doc in company.uploads_set.all %}
                                <h3>
                                    <a class='docLink' data-title='{{ doc.name }}' data-url="{{ doc.file.url|cut:'download' }}" data-name="{{ doc.file }}" data-toggle="modal" data-target="#docModal" aria-hidden="true"><i class="fa fa-file no-outline"></i> {{ doc.name }}</a>&emsp;<a href="{{ doc.file.url }}" download><i class="fa fa-download"></i></a></h3>
                                    <h4>{{ doc.details }}</h4>
                                    <br>
                            {% endfor %}
                            <hr>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
            {% endif %}
        </div>
    </div>
</div>

<div class="modal fade" id="docModal">
    <div class="modal-dialog modal-lg text-center" role="document">
        <div class="modal-content">
            <div class="modal-header bg-info">
                <h2 class="modal-title text-center" id="docTitle"></h2>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true" class="text-dark no-outline">×</span>
                </button>
            </div>
            <div class="modal-body bg-secondary">
                <div id='docUrl'><i class="fa fa-spinner fa-pulse"></i></div>
            </div>
            <div class="modal-footer bg-info">
                <button type="button" class="btn btn-secondary" data-dismiss="modal" >Close</button>
            </div>
        </div>
    </div>
</div>

<script>
    const docLinks = document.querySelectorAll('.docLink');
    const docTitle = document.querySelector('#docTitle');
    const docUrl = document.querySelector('#docUrl');

    for (let link of docLinks) {
        link.addEventListener('click', getDoc);
    }

    function getDoc() {
        docTitle.innerHTML = this.dataset.title;
        if (this.dataset.name.includes('.png') || this.dataset.name.includes('.jpg')) {
            setTimeout(() => { docUrl.innerHTML = `<img src='${this.dataset.url}' width=90% />`; }, 1000);
        } else if (this.dataset.name.includes('.doc') || this.dataset.name.includes('.pdf')) {
            setTimeout(() => { docUrl.innerHTML = `<iframe src="https://docs.google.com/gview?url=${this.dataset.url}&embedded=true" style="width:90%; height:600px;"></iframe>`; }, 1000);
        } else {
            setTimeout(() => { docUrl.innerHTML = '<h3>No preview available for this file type. Download the file instead to view.</h3>'; }, 1000);
        }
    }


    $('#docModal').on('shown.bs.modal', function () {
        $('.docLink').trigger('focus');
    });

    $("#docModal").on("hide.bs.modal", function () {
        docUrl.innerHTML = '<i class="fa fa-spinner fa-pulse"></i>';
    });
</script>

{% endblock %}

call_time/theater/getdata/templates/logout.html
{% extends 'base.html' %}
{% block body %}
    <br>
    <div class="container">
        <div class="row text-center">
            <div class="col-sm-12">
                <h1>Successfully Logged Out</h1>
            </div>
        </div>
        <br>
        <br>
        <div class="row text-center">
            <div class="col">
                <a href="{% url 'getdata:home' %}" class="btn btn-info">Return Home</a>
            </div>
        </div>
    </div>
{% endblock %}

call_time/theater/getdata/templates/profile.html
{% extends 'base.html' %}
{% block body %}
{% if error_message %}
    <h1>{{ error_message }}</h1>
{% endif %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-10 text-center">
            <br>
            <h1>Your Profile</h1>
            <br>
            <br>
        </div>
    </div>
    <div class="row">
        {% if user.groups.all.last.name == 'Artist' %}
            <div class="col-sm-5 mx-auto">
                <h2><u>Name</u>: {{ performer.first_name }} {{ performer.last_name }}<br><br>
                <u>Email</u>: {{ performer.email }} <br><br>
                <u>Phone</u>: {{ performer.phone }}<br><br>
                <u>Username</u>: {{ performer.username }}<br><br>
                {% if performer.roles_set.all.count > 0 %}
                    <u>Roles</u>:
                    {% for role in performer.roles_set.all %}
                        <a href="{% url 'getdata:roleinfo' role.id %}">{{ role.name }}</a> - <i>{{ role.show_id.title }}</i><br>
                    {% endfor %}
                {% endif %}
                <br>
                <u>Conflicts</u>:</h2>
                {% if performer.conflict_set.all.count > 0 %}
                    <ul>
                        {% for conflict in performer.conflict_set.all %}
                            <li><span>{{ conflict.start_date }}{% if conflict.end_date %} - {{ conflict.end_date }}{% endif %}</span>&emsp;{{ conflict.company.name }}</li>
                        {% endfor %}
                    </ul>
                {% else %}
                    None
                {% endif %}
                <br>
                {% if performer.username == user.username %}
                    <hr>
                    <h2><u>Receive email updates</u>: {% if performer.email_notifications == True %}<p class="text-success" style="-webkit-text-stroke: 0px white; display: inline-block;"> Yes </p>{% else %} <p class="text-danger" style="-webkit-text-stroke: 0px white; display: inline-block;"> No </p> {% endif %}</h2><br>
                    <form class="form-horizontal" action="{% url 'getdata:email-notice' %}" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-secondary">Change</button>
                            </div>
                        </div>
                    </form>
                    <br>
                    <p> Choose whether a company can email you schedules or other updates.</p>
                    <hr>
                    <h2><u>Profile</u>: <p class="text-warning" style="-webkit-text-stroke: 0px white; display: inline-block;">{% if performer.public_profile == True %} Public {% else %} Private {% endif %}</p></h2><br>
                    <form class="form-horizontal" action="{% url 'getdata:privacy' %}" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-warning text-white">Change</button>
                            </div>
                        </div>
                    </form><br>
                    <p>To hide your phone and email from other users, set Profile to Private.</p>
                    <hr>
                {% endif %}

                {% if performer.username == user.username %}
                    <form style="display: inline; margin-left: 5%; padding-bottom: 10%;" action="{% url 'getdata:performer-update' performer.id %}">
                        {% csrf_token %}
                        <input type="hidden" name="performer_id" value="{{ performer.id }}">&nbsp;
                        <button type="submit" class="btn btn-secondary">
                            <i class="fa fa-wrench"></i> Edit Profile
                        </button>&nbsp;&nbsp;
                    </form>&nbsp;
                    <button onclick="window.location.href=this.value" value="{% url 'getdata:user-update' user.id %}" class="btn btn-warning text-white">Change Password</button>
                {% endif %}
                <hr>
                <br>
            </div>
<!-- show personal schedule -->
 <!--need this code incase someone else tries to view another's full schedule-->
            <div class="col-sm-6" style="border-left: solid 2px white; padding-left: 50px;">
            {% if performer.calltime_set.all.count > 0 %}
                <h2><u> {{ performer.first_name }}'s Latest Schedule:</u></h2>
                <h3><span> {{ performer.calltime_set.all.last.date }}</span></h3>
                <h4><ul>
                {% for call in performer.calltime_set.all|dictsort:'start_time' %}
                    {% if call.date == performer.calltime_set.all.last.date %}
                        <br><li><u>{{ call.show_id_id.title }}:
                        {{ call.start_time|time:"g:i a" }}{% if call.end_time %} - {{ call.end_time|time:"g:i a" }}{% endif %}</u>
                        {% if call.headline %}
                            <br>{{ call.headline }}
                        {% endif %}
                        {% if call.venue_id %}
                            <br><br>{{ call.venue_id }} - {{ call.venue_id.location }}<br><br>
                        {% endif %}
                        {% if call.quickcall_set.all.count > 0 %}{% for q in call.quickcall_set.all %}{{ q.start_time|time:"g:i a" }}{% if q.end_time %} - {{ q.end_time|time:"g:i a" }}{% endif %}{% if q.details %} <u>{{ q.details }}</u>{% endif %}<br>{% endfor %}{% endif %}</li>
                        {% if call.notes %}<br>{{ call.notes }}<br>{% endif %}
                    {% endif %}
                {% endfor %}
                </ul></h4><br>
                <h4><a href="{% url 'getdata:callinfo' performer.calltime_set.all.last.id %}"><i class="fa fa-calendar"></i> See full schedule</a></h3>
            {% endif %}
            </div>
        {% elif user.groups.all.last.name == 'Company' %}
            <div class="col-md-12 pl-5">
                <h2><u>Name</u>: {{ self.name }} <br><br>
                    <u>Email</u>: {{ self.email }} <br><br>
                    <u>Username</u>: {{ self.username }}<br><br>
                    <u>Logo</u>: {% if self.logo %}<img style="width: 100px;" src="{{ self.logo.url }}">{% else %}None{% endif %}&nbsp;&nbsp;&nbsp;&nbsp;<button onclick="window.location.href=this.value" value="{% url 'getdata:logo' self.id %}" class="btn btn-info">Update Logo</button><br><br>
                    <a href="{% url 'getdata:staffinfo' %}"><i class="fa fa-clipboard-list no-outline"></i> View Staff</a><br><br>
                <div class="row pl-5">
                    <form class="d-flex align-content-center" style="display: inline-block; margin-left: 5%;" action="{% url 'getdata:company-update' self.id %}">
                        {% csrf_token %}
                        <input type="hidden" name="company_id" value="{{ self.id }}">
                        <button type="submit" class="btn btn-secondary my-auto">
                            <i class="fa fa-wrench"></i> Edit Profile
                        </button>&nbsp;&nbsp;
                    </form>
                    <button onclick="window.location.href=this.value" value="{% url 'getdata:user-update' user.id %}" class="btn btn-warning text-white my-auto">Change Password</button>
                </div>
            </div>
        {% endif %}
    </div>
</div>
<br><br>
<script>
    function Alert() {
        alert("An email alert has been sent to all staff and artists!");
    }
</script>
{% endblock %}